### ISSUE TITLE
Bar size relative to the containing card

### ISSUE THREAD

**Issue by g0r3** [custom-cards/bar-card#22]
Is it somehow possible to use a variable size in relation to the containing card? So that the bars get resized accordingly, when the size of the card gets changed?

**Comment by Gluwc** [comment]
Apologies for the late response. I'm not really sure what you mean, could you give an example?

**Comment by renjithstalin** [comment]
Instead of 100, can the bar be sized automatically for the target value? For example target:22, right now if I put target 22, for my car gas fuel tank capacity. Bar is in full size and the target is only shown as a dotted line.
BTW Thanks a bunch for this great card though, I'm literally creating bars for eveything just to show off this card :D
Thank You

**Comment by renjithstalin** [comment]
Sorry!! deleted my earlier post asking for sizing the graph as per the target, dumb me, later found the min/max options. Thanks a lot for this wonderful card.
