### ISSUE TITLE
Doesn't work anymore after upgrading to Home Assistant 0.110.1

### ISSUE THREAD

**Issue by gkron92** [custom-cards/bar-card#84]
Getting the custom element doiesn't exist: bar-card message.  Uninstalled and reinstalled from HACS and restarting HA didn't work.  Cleared cache too and no help.  Here are the log messages

https://xxxxxxxxx.duckdns.org/hacsfiles/bar-card/bar-card.js:5355:1 Uncaught SyntaxError: Unexpected token 'export'

Tried to serve up '/config/www/community/bar-card/bar-card.js' but it does not exist

I checked the folder and bar-card folder and bar-card.js are there.

**Comment by anup92k** [comment]
I've got a similar issue :
```
https://my.domaine.tld:1111/hacsfiles/bar-card/bar-card.js:5355:0 SyntaxError: export declarations may only appear at top level of a module
:0:0 ResizeObserver loop completed with undelivered notifications.
```
And also got that `bar-card` doesn't exist.

I've managed to get is working following these steps :
- Uninstall `bar-card` in HACS
- Remove the ressource in Lovelace (Config > Dashboard > Ressources)
- Install `bar-card`

Now, my card is working as before.

Hope it solve your issue.

**Comment by gkron92** [comment]
Thank you. This worked.

**Comment by Cezero** [comment]
same issue as parent: /bar-card.js:5355:0 SyntaxError: Unexpected keyword 'export'
Uninstall, reinstall doesn't resolve.

**Comment by anup92k** [comment]
> 
> 
> same issue as parent: /bar-card.js:5355:0 SyntaxError: Unexpected keyword 'export'
> Uninstall, reinstall doesn't resolve.

Did you remove the ressource after uninstalling ?

**Comment by Cezero** [comment]
I removed the resource from my config.yaml   I don't use dashboard config

**Comment by anup92k** [comment]
So you have removed from your file the reference to `/hacsfiles/bar-card/bar-card.js` or something like `/local/my-custom-card.js` according to [the doc](https://www.home-assistant.io/lovelace/dashboards-and-views/).
Maybe after that, you have to reload HA (check_config and restart HA) or maybe you need to manually delete the JSON file.

**Comment by Cezero** [comment]
I switched to dashboard config, now it's working.

**Comment by cmlittle** [comment]
I also ran into this issue when upgrading to 0.110.x. I was able to fix this running in YAML mode by uninstalling `bar-card` in HACS, then commenting out the bar-card `url` and `type` in my `ui-Lovelace.yaml`. I then restarted HA, reinstalled `bar-card` in HACS, uncommented the`bar-card` `url` and `type` and changed type from `js` to `module`. I'm wondering if this could just be fixed by changing the type from js to module in the yaml configuration without performing all of these other steps. It seems somewhere the type switched from js to module without notice.

**Comment by rschuiling** [comment]
I think it would be great if the documentation mentioned what to add in resources.yaml. It is not mentioned that the type should be 'module' instead of 'js'. It has cost me a lot of time and thanks to this issue I found this little nugget of information.

@Gluwc As a suggestion: can you add this to the documentation page? Perhaps also the mentioned steps: remove from resources.yaml, remove from HACS, reinstall from HACS, add to resources.yaml again (type 'module'), clear cache and refresh Lovelace. This worked for me.

**Comment by Gluwc** [comment]
Added to documentation.
